[package]
name = "ulferno/bloxql"
description = "A GraphQL client for Roblox"
version = "0.0.3"
license = "GPLv3"
author = "ulferno, goldyydev"
registry = "https://github.com/upliftgames/wally-index"
repo = "https://github.com/BritSovInteractive/BloxQL"
realm = "shared"
exclude = ["**"]
include = ["lib", "lib/**", "wally.toml", "wally.lock", "default.project.json"]